### ISSUE TITLE
Problem with the AsHTTPBodyReader function

### ISSUE THREAD

**Issue by mar-coding** [emcfarlane/larking#108]
I'm facing a problem while using your uploader. Whenever I upload a file, the uploader adds some header and footer data that corrupts my files. As a result, I can't open my images. Could you please explain what I should do to solve this problem?

data before upload: this is te2st@
data after upload:
----------------------------809015558382901059574012
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

this is te2st@

----------------------------809015558382901059574012--

**Comment by emcfarlane** [comment]
Hey @mar-coding,  thanks for making the issue. Could you add a bit more context? Or a snippet of your current code? Thanks
