### ISSUE TITLE
How about automatically importing HttpRule

### ISSUE THREAD

**Issue by kooksee** [emcfarlane/larking#113]
- I want to know how to import the HttpRule defined in protobuf through larking
- I have learned that Larking imports grpc service through RegisterService, and I noticed that the code inside does not handle the HttpRule of the method
- If I want to automatically import the HttpRule defined in protobuf, I don't know what to do?

**Comment by emcfarlane** [comment]
Hey @kooksee , hopefully the issue is solved for you? But please check out vanguard-go as a replacement for this library:  https://github.com/connectrpc/vanguard-go
